// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_writer_addstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_writer_addstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202105222323154_add_writer_addstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
